# Axis Parameter

## What is axis?
axis refers to the specific dimension/direction along which an operation is performed in an array.

* **Axis 0** (Operation along rows) → Operates on **columns** (i.e., calculates across each column)

* **Axis 1** (Operation along columns) → Operates on **rows** (i.e., calculates across each row)

[[ 1  2  3  4]   ← axis=1 → [1+2+3+4 = 10]  
 [ 5  6  7  8]   ← axis=1 → [5+6+7+8 = 26]    
 [ 9 10 11 12]]  ← axis=1 → [9+10+11+12 = 42]  

  ↑  ↑  ↑  ↑  
  |  |  |  |  
  ↓  ↓  ↓  ↓  
  [15,18,21,24]

In [2]:
import numpy as np

In [3]:
# 3x4 sample matrix
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original matrix:\n", matrix)
print("Shape of array: ", matrix.shape)

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array:  (3, 4)


In [4]:
# Sum all elements in the list
print("Sum of array:", matrix.sum())

# axis=0: Along columns (one value per column)
print("axis=0 (along columns):")
print(
    "Sum: ", np.sum(matrix, axis=0)
)  # [1+5+9, 2+6+10, 3+7+11, 4+8+12] = [15, 18, 21, 24]
print("Mean: ", np.mean(matrix, axis=0))  # [5, 6, 7, 8]


# axis=1: Along columns (one value per column)
# The sum of all elements in the line
print("Sum: ", np.sum(matrix, axis=1))  # [1+2+3+4, 5+6+7+8, 9+10+11+12] = [10, 26, 42]
print("Mean: ", np.mean(matrix, axis=1))  # [2.5, 6.5, 10.5]

Sum of array: 78
axis=0 (along columns):
Sum:  [15 18 21 24]
Mean:  [5. 6. 7. 8.]
Sum:  [10 26 42]
Mean:  [ 2.5  6.5 10.5]


# Array Summation: np.sum()

In [5]:
# Create a simple array
a = np.array([1, 2, 3, 4, 5])

print("Array: \n", a)


# Sum of all elements
total = np.sum(a)
print("Total Sum: \n", total)  # Output: 15

Array: 
 [1 2 3 4 5]
Total Sum: 
 15


In [6]:
# 2D array example
b = np.array([[1, 2, 3], [4, 5, 6]])


print("2D Array:\n", b)

# Sum of all elements\n",
print("Total sum: \n", np.sum(b))  # 21

# Sum along rows (axis=1)\n",
print("Row sums: \n", np.sum(b, axis=1))  # [6, 15]

# Sum along columns (axis=0)\n",
print("Column sums: \n", np.sum(b, axis=0))  # [5, 7, 9]

# np.sum() returns the sum of all elements in an array.\n",
# For multi-dimensional arrays, you can specify an axis to sum along rows or columns.\n",

# axis=0 → operates along columns (rows are collapsed)\n",
# axis=1 → operates along rows (columns are collapsed)"


2D Array:
 [[1 2 3]
 [4 5 6]]
Total sum: 
 21
Row sums: 
 [ 6 15]
Column sums: 
 [5 7 9]


# Calculating Mean: `np.mean()`

Note: Mean is calculated as `sum / number_of_elements`. `np.mean()` handles this automatically.

In [7]:
# Using the same array\n",
a = np.array([1, 2, 3, 4, 5])
mean_val = np.mean(a)
print("Mean: \n", mean_val)  # 3.0

np.median(a)  # Returns the middle value\n",

# 2D array example
b = np.array([[1, 2, 3], [4, 5, 6]])

print("Overall mean: \n", np.mean(b))  # 3.5
print("Row means: \n", np.mean(b, axis=1))  # [2.0, 5.0]
print("Column means: \n", np.mean(b, axis=0))  # [2.5, 3.5, 4.5]"

Mean: 
 3.0
Overall mean: 
 3.5
Row means: 
 [2. 5.]
Column means: 
 [2.5 3.5 4.5]


# Standard Deviation: `np.std()` 

Standard deviation shows how spread out the data is.

**Steps to calculate standard deviation:**
1. Calculate the arithmetic mean of the data.
2. Square each difference, 
3. then sum them up.
4. Divide the sum by `(N-1)` for sample standard deviation, then take the square root.


💡 **Tip:** By default, NumPy calculates the **population** standard deviation (divides by `N`). If you want the **sample** standard deviation, add the `ddof=1` parameter:
`np.std(a, ddof=1)`"

In [8]:
a = np.array([1, 2, 3, 4, 5])
std_dev = np.std(a)

print("Standard Deviation: \n", std_dev)  # ~1.414

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Overall Std Dev: \n", np.std(b))
print("Row-wise Std Dev: \n", np.std(b, axis=1))
print("Column-wise Std Dev: \n", np.std(b, axis=0))

Standard Deviation: 
 1.4142135623730951
Overall Std Dev: 
 1.707825127659933
Row-wise Std Dev: 
 [0.81649658 0.81649658]
Column-wise Std Dev: 
 [1.5 1.5 1.5]


In [9]:
# Sum, Standard Deviation, Mean, Max - Min

# Sample Data: Grades of 5 students across 3 exams (5x3 Matrix)
# Rows: Students, Columns:Exams
grades = np.array(
    [[90, 85, 70], [60, 75, 80], [95, 90, 92], [70, 65, 88], [80, 70, 75]]
)
print("Grades Matrix (5x3):\n", grades)

# a) Sum: Total of the entire array
total_grades = np.sum(grades)
print(f"\n1. Total Grade Sum: {total_grades}")

# b) Mean: Average of the entire array
mean_grade = np.mean(grades)
print(f"2. Overall Average: {mean_grade:.2f}")

# c) Standard Deviation: How spread out the grades are
std_dev = np.std(grades)
print(f"3. Standard Deviation: {std_dev:.2f}")

# d) Min/Max: Lowest and highest grades
min_grade = np.min(grades)
max_grade = np.max(grades)
print(f"4. Lowest Grade: {min_grade}")
print(f"5. Highest Grade: {max_grade}")

Grades Matrix (5x3):
 [[90 85 70]
 [60 75 80]
 [95 90 92]
 [70 65 88]
 [80 70 75]]

1. Total Grade Sum: 1185
2. Overall Average: 79.00
3. Standard Deviation: 10.39
4. Lowest Grade: 60
5. Highest Grade: 95


In [10]:
# 1. axis=0: Exam Averages (Operation along columns)
exam_averages = grades.mean(axis=0)
print(f"Exam Averages (Axis=0):\n{exam_averages.round(2)}")
# Output: [79.00 77.00 81.00] (Average for each exam)

# 2. axis=1: Student Averages (Operation along rows)
student_averages = grades.mean(axis=1)
print(f"\nStudent Averages (Axis=1):\n{student_averages.round(2)}")
# Output: [81.67 71.67 92.33 74.33 75.00] (Average for each student)

Exam Averages (Axis=0):
[79. 77. 81.]

Student Averages (Axis=1):
[81.67 71.67 92.33 74.33 75.  ]


In [11]:
# Argmin / Argmax: Returns the INDEX of the min/max value, not the value itself.

# Overall: Flattened index of the highest grade in the array
highest_idx = grades.argmax()
print(f"Overall Index of Highest Grade: {highest_idx}")  # 7 (position of 95)

# Axis=1: Index of the highest exam for each student
highest_exam_idx = grades.argmax(axis=1)
print(f"Highest Exam Index per Student (Axis=1): {highest_exam_idx}")
# Output: [0 2 0 2 0] -> Student 1 highest in exam 0, Student 2 in exam 2, etc.

# Cumulative Operations (cumsum): Running Total
# Real-world example: Cumulative daily sales
daily_sales = np.array([100, 150, 80, 200, 120])
cumulative_sales = daily_sales.cumsum()
print(f"\nCumulative Sales: {cumulative_sales}")
# Output: [100 250 330 530 650]"

Overall Index of Highest Grade: 6
Highest Exam Index per Student (Axis=1): [0 2 0 2 0]

Cumulative Sales: [100 250 330 530 650]


In [12]:
# Cumulative product
growth = np.array([1.10, 1.20, 1.05])
np.cumprod(growth)  # [1.10, 1.32, 1.386]"

array([1.1  , 1.32 , 1.386])

### **Other Statistical Operations:**

✔ `diff()` → consecutive differences <br>
✔ `sort()` & `argsort()` → sorting & index ordering<br>
✔ `unique()` → unique values<br>
✔ `where()` → conditional indexing<br>
✔ `percentile()` → percentile analysis (important in statistics)

In [13]:
"""
np.diff() → Consecutive Differences

Returns the differences between consecutive elements in an array.
"""

a = np.array([10, 15, 20, 18, 30])
print(np.diff(a))

[ 5  5 -2 12]


# `sort()` & `argsort()` → Sorting & Index Order

In [14]:
x = np.array([3, 1, 5, 4])
print(np.sort(x))
print(np.argsort(x))

[1 3 4 5]
[1 0 3 2]


# `np.unique` → Unique Values

In [15]:
a = np.array([1, 2, 3, 3, 2, 4, 5, 5])
print(np.unique(a))

# To get frequencies
values, counts = np.unique(a, return_counts=True)
print(values, counts)

[1 2 3 4 5]
[1 2 3 4 5] [1 2 2 1 2]


# `np.percentile()` → Percentile Analysis

Fundamental for boxplots, highly important in ML and data analysis.

In [16]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(np.percentile(data, 50))  # Median
print(np.percentile(data, 25))  # Q1
print(np.percentile(data, 75))  # Q3

45.0
27.5
62.5


# Using `np.all` and `np.any`"

In [17]:
arr = np.random.randint(1, 10, (5, 5))
print(arr)

print(np.all(arr > 5))
print(np.all(arr > 2))

print(np.any(arr >= 9))
print(np.any(arr > 8))

[[3 2 1 3 9]
 [6 4 7 2 1]
 [5 6 6 7 5]
 [2 8 2 3 9]
 [5 3 6 5 8]]
False
False
True
True


# Conditional Operations with `np.where`
Used for value assignment and filtering.

In [18]:
# Basic Usage: Condition → If True X, Else Y

a = np.array([1, 2, 3, 4, 5])

# If element > 3, label "high", else "low"
result = np.where(a > 3, "high", "low")
print(result)  # ['low' 'low' 'low' 'high' 'high']

['low' 'low' 'low' 'high' 'high']


In [19]:
# Usage with Numeric Values
# If element > 3, set 100, else -100
b = np.where(a > 3, 100, -100)
print(b)  # [-100 -100 -100  100  100]

[-100 -100 -100  100  100]


In [20]:
# Finding Indices that Satisfy a Condition

# Get indices where a > 3
indices = np.where(a > 3)
print("Indices satisfying condition: ", indices[0])  # [3 4]

# Use these indices to extract values
print("Values satisfying condition: ", a[indices])  # [4 5]


"""
Alternative: You can filter directly using a[a > 3].
`np.where` is more flexible because it supports ternary (condition, true, false) logic.
"""

Indices satisfying condition:  [3 4]
Values satisfying condition:  [4 5]


'\nAlternative: You can filter directly using a[a > 3].\n`np.where` is more flexible because it supports ternary (condition, true, false) logic.\n'

In [21]:
# Real-world Example: Creating a Profitability Column
# Profit: > 0, Loss: < 0, Neutral: = 0
revenues = np.array([1000, 800, 1200, 950])
costs = np.array([850, 900, 1100, 950])

profit_loss = revenues - costs
print(f"Profit/Loss: {profit_loss}")  # [ 150 -100  100    0]

# Conditional Mapping 1: Positive → 1, Negative → -1, Zero → 0
pl_status = np.where(
    profit_loss > 0,
    1,  # Profit
    np.where(profit_loss < 0, -1, 0),
)  # Loss or Neutral
print(f"P/L Status (1, -1, 0): {pl_status}")

# Real-world Example 2: Data Clipping (Outlier Cleaning)
# Clamp grades between 50 and 100 (replace <50 with 50)
class_grades = np.array([30, 75, 105, 45, 90])

clamped_grades = np.where(
    class_grades < 50,
    50,  # If <50, set to 50
    np.where(class_grades > 100, 100, class_grades),
)  # If >100, set to 100, else keep
print(f"\nClamped Grades: {clamped_grades}")

Profit/Loss: [ 150 -100  100    0]
P/L Status (1, -1, 0): [ 1 -1  1  0]

Clamped Grades: [ 50  75 100  50  90]


In [22]:
# Advanced np.where problems

print("\n" + "=" * 60)
print("=== 3. np.where() and CONDITIONAL OPERATIONS ===\n")

# Example: Conditional operations on student grades
student_grades = np.array([45, 67, 82, 91, 58, 73, 39, 88, 76, 62, 55, 95])
print("Student grades: ", student_grades)

# 3.1 BASIC np.where() USAGE
print("\n3.1 BASIC np.where() USAGE:")

# Condition: Grade >= 60 → "Passed", else "Failed"
statuses = np.where(student_grades >= 60, "Passed", "Failed")

# 3.2 NESTED np.where() - MULTIPLE CONDITIONS
print("\n3.2 NESTED np.where() - LETTER GRADES:")

letter_grades = np.where(
    student_grades >= 90,
    "A",
    np.where(
        student_grades >= 80,
        "B",
        np.where(student_grades >= 70, "C", np.where(student_grades >= 60, "D", "F")),
    ),
)

print("Letter grades: ", letter_grades)

# 3.3 FINDING INDICES THAT SATISFY A CONDITION
print("\\n3.3 INDICES SATISFYING CONDITIONS:")

passed_indices = np.where(student_grades >= 60)[0]
failed_indices = np.where(student_grades < 60)[0]

print(f"Passed student indices: {passed_indices}")
print(f"Passed student grades: {student_grades[passed_indices]}")
print(f"Number of failed students: {len(failed_indices)}")

# 3.4 np.select() - MORE READABLE MULTIPLE CONDITIONS
print("\n3.4 MULTIPLE CONDITIONS WITH np.select():")

conditions = [
    student_grades >= 90,  # Condition 1: A
    (student_grades >= 80) & (student_grades < 90),  # Condition 2: B
    (student_grades >= 70) & (student_grades < 80),  # Condition 3: C
    (student_grades >= 60) & (student_grades < 70),  # Condition 4: D
    student_grades < 60,  # Condition 5: F
]

choices = ["Excellent", "Good", "Average", "Passing", "Failing"]

grading = np.select(conditions, choices, default="Unknown")
print("Grading: ", grading)

# 3.5 CONDITIONAL VALUE ASSIGNMENT & BINNING
print("\n3.5 CONDITIONAL BINNING:")

# Categorize grades into 10-point bins
bins = np.digitize(student_grades, bins=[0, 50, 60, 70, 80, 90, 100])
bin_labels = ["0-49", "50-59", "60-69", "70-79", "80-89", "90-100"]
categorized = [bin_labels[i - 1] for i in bins]

print("Grade bins: ", categorized)

# 3.6 REAL-WORLD APPLICATION: SALARY BONUS CALCULATION
print("\n3.6 REAL-WORLD APP - SALARY BONUS:")

salaries = np.array([25000, 32000, 18000, 45000, 28000, 38000, 22000])
performance = np.array([85, 92, 65, 95, 78, 88, 72])  # 0-100 scale

# Bonus rates based on performance
bonus_rates = np.where(
    performance >= 90,
    0.15,  # 15% bonus
    np.where(
        performance >= 80,
        0.10,  # 10% bonus
        np.where(performance >= 70, 0.05, 0.02),
    ),
)  # 5% or 2% bonus

new_salaries = salaries * (1 + bonus_rates)

print("Old salaries: ", salaries)
print("Performance scores: ", performance)
print("Bonus rates: ", bonus_rates)
print("New salaries: ", new_salaries.astype(int))

"""
PERFORMANCE COMPARISON:\n",
NumPy (Vectorized) vs Python (Loop-based)\n",

NumPy advantages:\n",
- Faster (C-level optimized)\n",
- Lower memory usage\n",
- More readable code\n",
- Parallel processing benefits\n",
"""


=== 3. np.where() and CONDITIONAL OPERATIONS ===

Student grades:  [45 67 82 91 58 73 39 88 76 62 55 95]

3.1 BASIC np.where() USAGE:

3.2 NESTED np.where() - LETTER GRADES:
Letter grades:  ['F' 'D' 'B' 'A' 'F' 'C' 'F' 'B' 'C' 'D' 'F' 'A']
\n3.3 INDICES SATISFYING CONDITIONS:
Passed student indices: [ 1  2  3  5  7  8  9 11]
Passed student grades: [67 82 91 73 88 76 62 95]
Number of failed students: 4

3.4 MULTIPLE CONDITIONS WITH np.select():
Grading:  ['Failing' 'Passing' 'Good' 'Excellent' 'Failing' 'Average' 'Failing'
 'Good' 'Average' 'Passing' 'Failing' 'Excellent']

3.5 CONDITIONAL BINNING:
Grade bins:  ['0-49', '60-69', '80-89', '90-100', '50-59', '70-79', '0-49', '80-89', '70-79', '60-69', '50-59', '90-100']

3.6 REAL-WORLD APP - SALARY BONUS:
Old salaries:  [25000 32000 18000 45000 28000 38000 22000]
Performance scores:  [85 92 65 95 78 88 72]
Bonus rates:  [0.1  0.15 0.02 0.15 0.05 0.1  0.05]
New salaries:  [27500 36800 18360 51749 29400 41800 23100]


'\nPERFORMANCE COMPARISON:\n",\nNumPy (Vectorized) vs Python (Loop-based)\n",\n\nNumPy advantages:\n",\n- Faster (C-level optimized)\n",\n- Lower memory usage\n",\n- More readable code\n",\n- Parallel processing benefits\n",\n'

# `np.nan` Not a Number

`np.nan` (Not a Number) represents missing or undefined numerical data.

In real-world datasets, missing values (NaN) are frequently encountered.

In [23]:
# np.nan is a special value
print(np.nan)  # nan

# Any comparison with np.nan returns False!
print(np.nan == np.nan)  # False ❗
print(np.nan is np.nan)  # True (but not reliable for checks)

# Correct check: np.isnan()
print(np.isnan(np.nan))  # True

nan
False
True
True


In [24]:
# Statistics with NaN

data = np.array([1, 2, np.nan, 4, 5])
print("Data: ", data)

# Standard mean → returns nan!
print("Standard mean: ", np.mean(data))  # nan

# Ignore NaNs for mean → np.nanmean()
print("Mean ignoring NaNs: ", np.nanmean(data))  # 3.0

# Similarly:
print("Sum (ignoring NaN): ", np.nansum(data))  # 12.0
print("Std Dev (ignoring NaN): ", np.nanstd(data))  # ~1.58

# Rule: When dealing with arrays containing np.nan,
# use np.nan... functions (nanmean, nanstd, nansum, etc.)

Data:  [ 1.  2. nan  4.  5.]
Standard mean:  nan
Mean ignoring NaNs:  3.0
Sum (ignoring NaN):  12.0
Std Dev (ignoring NaN):  1.5811388300841898


In [25]:
# If value < 3, set to nan, else keep original
data2 = np.where(data < 3, np.nan, data)
print("New data: ", data2)  # [nan nan nan 4. 5.]

# Calculate mean (ignoring NaNs)
print("Mean: ", np.nanmean(data2))  # 4.5

New data:  [nan nan nan  4.  5.]
Mean:  4.5


In [26]:
# Create an array with missing data
data_nan = np.array([10, 20, np.nan, 40, 50])
print(f"Array with Missing Data: {data_nan}")

# Standard stats fail with NaN!
normal_mean = np.mean(data_nan)
print(f"\nStandard Mean (corrupted by NaN): {normal_mean}")
# Output: nan

# np.isnan(): Check which elements are missing
nan_mask = np.isnan(data_nan)
print(f"np.isnan() Mask: {nan_mask}")
# Output: [False False  True False False]

Array with Missing Data: [10. 20. nan 40. 50.]

Standard Mean (corrupted by NaN): nan
np.isnan() Mask: [False False  True False False]


In [27]:
# NaN-Aware Statistics: Skip missing data to get correct
nan_aware_mean = np.nanmean(data_nan)
print(f"NaN-Aware Mean (np.nanmean): {nan_aware_mean:.2f}")
# Output: 30.00 ( (10+20+40+50) / 4 )

# NaN-Aware Sum
nan_aware_sum = np.nansum(data_nan)
print(f"NaN-Aware Sum (np.nansum): {nan_aware_sum}")
# Output: 120.0"

NaN-Aware Mean (np.nanmean): 30.00
NaN-Aware Sum (np.nansum): 120.0


In [28]:
# Comprehensive NaN examples

print("\n" + "=" * 60)
print("=== 4. NaN VALUES & MISSING DATA MANAGEMENT ===\n")

# 4.1 CREATING & DETECTING NaN
print("4.1 CREATING & DETECTING NaN:")

# Sensor data example (some measurements failed)
sensor_data = np.array([23.5, 24.1, np.nan, 25.8, np.nan, 26.3, 24.9, np.nan, 25.5])
print("Sensor data (with NaNs): ", sensor_data)

# NaN detection functions
nan_mask = np.isnan(sensor_data)
print("NaN mask (True=NaN): ", nan_mask)
print("Total NaN count: ", np.sum(nan_mask))
# Select non-NaN values
valid_data = sensor_data[~nan_mask]  # ~ operator: NOT
print("Valid data: ", valid_data)

# 4.2 NaN-FRIENDLY STATISTICAL FUNCTIONS
print("\n4.2 NaN-FRIENDLY FUNCTIONS:")

print("Standard mean (fails with NaNs): ", np.mean(sensor_data))
print("NaN-friendly mean: ", np.nanmean(sensor_data))
print("NaN-friendly std dev: ", np.nanstd(sensor_data))
print("NaN-friendly sum: ", np.nansum(sensor_data))
print("NaN-friendly min: ", np.nanmin(sensor_data))

# 4.3 MISSING DATA IMPUTATION STRATEGIES
print("\n4.3 MISSING DATA IMPUTATION STRATEGIES:")

# Strategy 1: Fill with constant
filled_1 = sensor_data.copy()
filled_1[nan_mask] = 0
print("1. Filled with 0: ", filled_1)

# Strategy 2: Fill with mean
mean_val = np.nanmean(sensor_data)
filled_2 = sensor_data.copy()
filled_2[nan_mask] = mean_val
print("2. Filled with mean: ", filled_2)

# Strategy 3: Fill with median
median_val = np.nanmedian(sensor_data)
filled_3 = sensor_data.copy()
filled_3[nan_mask] = median_val
print("3. Filled with median: ", filled_3)

# 4.4 LINEAR INTERPOLATION
print("\n4.4 LINEAR INTERPOLATION:")


def linear_interpolate(arr):
    """Fills NaN values using linear interpolation."""
    nans = np.isnan(arr)
    # Find non-NaN indices
    x = lambda z: z.nonzero()[0]
    # Apply interpolation
    arr[nans] = np.interp(x(nans), x(~nans), arr[~nans])
    return arr


interp_data = linear_interpolate(sensor_data.copy())
print("Interpolated data: ", interp_data)

# 4.5 WORKING WITH INFINITY
print("\n4.5 WORKING WITH INFINITY:")

inf_arr = np.array([1, 2, np.inf, 4, -np.inf, 6, np.nan])
print("Original array: ", inf_arr)
print("Is infinite: ", np.isinf(inf_arr))
print("Is finite: ", np.isfinite(inf_arr))
print("Is NaN: ", np.isnan(inf_arr))

# Clean infinite values
finite_data = inf_arr[np.isfinite(inf_arr)]
print("Finite values: ", finite_data)

# 4.6 REAL-WORLD APP: WEATHER DATA
print("\n4.6 REAL-WORLD APP - TEMPERATURE DATA:")

# 7-day temperature (some days unmeasured)
temp_data = np.array([22.5, np.nan, 24.1, 23.8, np.nan, 25.2, 24.7])
print("Raw temperature data: ", temp_data)

# Missing data analysis
print("Missing data count: ", np.sum(np.isnan(temp_data)))
print("Missing data ratio: %{:.1f}".format(np.mean(np.isnan(temp_data)) * 100))

# Compare multiple imputation strategies
strategies = {
    "Mean": np.nanmean(temp_data),
    "Median": np.nanmedian(temp_data),
    "Neighbor Avg": np.nanmean([22.5, 24.1]),  # Prev & next values
    "Seasonal Avg": 23.0,  # Historical baseline
}

print("\\nImputation strategy comparison:")
for strat, val in strategies.items():
    complete = temp_data.copy()
    complete[np.isnan(temp_data)] = val
    print(f"  {strat}: {complete}")

"""
MISSING DATA STRATEGY SELECTION:
- Small datasets: Interpolation or neighbor values
- Large datasets: Mean/Median imputation
- Time series: Forward fill
- Critical applications: Multiple imputation methods
"""


=== 4. NaN VALUES & MISSING DATA MANAGEMENT ===

4.1 CREATING & DETECTING NaN:
Sensor data (with NaNs):  [23.5 24.1  nan 25.8  nan 26.3 24.9  nan 25.5]
NaN mask (True=NaN):  [False False  True False  True False False  True False]
Total NaN count:  3
Valid data:  [23.5 24.1 25.8 26.3 24.9 25.5]

4.2 NaN-FRIENDLY FUNCTIONS:
Standard mean (fails with NaNs):  nan
NaN-friendly mean:  25.01666666666667
NaN-friendly std dev:  0.9702519718551924
NaN-friendly sum:  150.10000000000002
NaN-friendly min:  23.5

4.3 MISSING DATA IMPUTATION STRATEGIES:
1. Filled with 0:  [23.5 24.1  0.  25.8  0.  26.3 24.9  0.  25.5]
2. Filled with mean:  [23.5        24.1        25.01666667 25.8        25.01666667 26.3
 24.9        25.01666667 25.5       ]
3. Filled with median:  [23.5 24.1 25.2 25.8 25.2 26.3 24.9 25.2 25.5]

4.4 LINEAR INTERPOLATION:
Interpolated data:  [23.5  24.1  24.95 25.8  26.05 26.3  24.9  25.2  25.5 ]

4.5 WORKING WITH INFINITY:
Original array:  [  1.   2.  inf   4. -inf   6.  nan]
Is inf

'\nMISSING DATA STRATEGY SELECTION:\n- Small datasets: Interpolation or neighbor values\n- Large datasets: Mean/Median imputation\n- Time series: Forward fill\n- Critical applications: Multiple imputation methods\n'

# File I/O with `np.loadtxt()`:

In [29]:
# Create a file in Colab/Local
# Sample data file
data_content = """1.0,2.0,3.0
4.0,5.0,6.0
7.0,8.0,9.0"""

# Save to file
with open("data.csv", "w") as f:
    f.write(data_content)

print("data.csv file created.")

data.csv file created.


In [30]:
# Load comma-separated data
data = np.loadtxt("data.csv", delimiter=",")
print("Loaded data:\n", data)
print("Shape: ", data.shape)  # (3, 3)

Loaded data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Shape:  (3, 3)


In [31]:
# Create a file with headers
data_header = """x,y,z
1.0,2.0,3.0
4.0,5.0,6.0
7.0,8.0,9.0"""

with open("data_header.csv", "w") as f:
    f.write(data_header)

# If your file has column names, use skiprows:
# Skip the first row
data2 = np.loadtxt("data_header.csv", delimiter=",", skiprows=1)
print("Header-less data:\n", data2)

Header-less data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [32]:
# File with missing data
data_nan = """1.0,2.0,3.0
4.0,,6.0
7.0,8.0,"""

with open("data_nan.csv", "w") as f:
    f.write(data_nan)

# Empty cells may cause errors in loadtxt
try:
    data3 = np.loadtxt("data_nan.csv", delimiter=",")
except ValueError as e:
    print("Error: ", e)
    print("np.loadtxt cannot automatically parse empty cells as NaN.")

Error:  could not convert string '' to float64 at row 1, column 2.
np.loadtxt cannot automatically parse empty cells as NaN.


In [33]:
# 🛠️ Solution: np.genfromtxt() is more flexible and handles missing values.

data3 = np.genfromtxt("data_nan.csv", delimiter=",", filling_values=np.nan)
print("Loaded with missing values:\n", data3)
print("Mean (ignoring NaN): ", np.nanmean(data3))

# Recommendation: Use loadtxt for clean numeric data, genfromtxt for complex/missing data.

Loaded with missing values:
 [[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. nan]]
Mean (ignoring NaN):  4.428571428571429


Used to directly load text-based (CSV, TXT) files into NumPy arrays.

Syntax: `np.loadtxt(fname, delimiter=' ', skiprows=0, dtype=float)`

In [ ]:
# Step 1: Create a sample CSV (for practice)
# Data: Temperature, Humidity, Wind Speed
weather_str = """Temp,Humid,Wind
22.5,55.0,15.0
23.1,52.5,18.0
22.9,53.0,16.5"""

with open("weather_data.csv", "w") as f:
    f.write(weather_str)
print("weather_data.csv created.")

# Step 2: Load with np.loadtxt
try:
    weather_np = np.loadtxt(
        "weather_data.csv", delimiter=",", skiprows=1, dtype=np.float64
    )
    print(f"\n✅ Loaded NumPy Array (Shape: {weather_np.shape}):\n{weather_np}")
except Exception as e:
    print(f"Error: {e}")

# Step 3: Calculate statistics using axis
# Column-wise mean (Avg Temp, Humidity, Wind)
avg_metrics = weather_np.mean(axis=0)
print(f"\nAvg Temp, Humidity, Wind: {avg_metrics.round(2)}")

weather_data.csv created.

✅ Loaded NumPy Array (Shape: (3, 3)):
[[22.5 55.  15. ]
 [23.1 52.5 18. ]
 [22.9 53.  16.5]]

Avg Temp, Humidity, Wind: [22.83 53.5  16.5 ]


# Saving Data: `np.savetxt()`
Save processed/transformed NumPy arrays to disk.

Syntax: `np.savetxt(fname, X, fmt='%.18e', delimiter=' ')`

In [36]:
# Save the loaded data
# fmt='%.2f': float precision to 2 decimals
# delimiter=',': Use comma separator
np.savetxt(
    "processed_weather.csv",
    weather_np,
    fmt="%.2f",
    delimiter=",",
    header="Temp,Humid,Wind",
    comments="# ",
)  # Add header and set comment char

print("\n'processed_weather.csv' saved (2 decimal precision).")

# Verify content
with open("processed_weather.csv", "r") as f:
    print("\nSaved File Content:")
    print(f.read())


'processed_weather.csv' saved (2 decimal precision).

Saved File Content:
# Temp,Humid,Wind
22.50,55.00,15.00
23.10,52.50,18.00
22.90,53.00,16.50



# Mini Project

**Goal:** Read a data file, detect missing values, calculate mean & standard deviation.

In [40]:
# Comprehensive file operations examples

print("\n" + "=" * 60)
print("=== 5. FILE OPERATIONS - np.loadtxt() & np.genfromtxt() ===\n")


# 5.1 CREATE SAMPLE CSV

csv_content = """name,age,salary,dept,gender
Jack,25,50000,Eng,M
Jim,30,60000,Sales,F
Jimmy,35,75000,Eng,M
Jill,28,55000,HR,F
John,32,48000,Sales,F
Janet,29,,Eng,M
Jonathon,27,52000,HR,F
Jayson,31,68000,Sales,M"""


with open("employees.csv", "w", encoding="utf-8") as f:
    f.write(csv_content)

print("CSV created: employees.csv")

# 5.2 np.loadtxt() - FOR CLEAN FILES\n",
print("\n5.2 np.loadtxt() - FOR SIMPLE FILES:")

try:
    numeric_data = np.loadtxt(
        "employees.csv", delimiter=",", skiprows=1, usecols=(1, 2), encoding="utf-8"
    )
    print("loadtxt() success:\n", numeric_data)
except Exception as e:
    print(f"loadtxt() error: {e}")
    print("Reason: Fails on missing data (NaN)")

# 5.3 np.genfromtxt() - ADVANCED READING\n",
print("\n5.3 np.genfromtxt() - ADVANCED READING:")

data = np.genfromtxt(
    "employees.csv",
    delimiter=",",
    skip_header=1,
    dtype=None,
    encoding="utf-8",
    missing_values="",
    filling_values=0,
)

print("Data loaded with genfromtxt():")
print(data)
print("Data type: ", data.dtype)
print("Shape: ", data.shape)

# 5.4 CONTROLLED COLUMN READING\n",
print("\n5.4 CONTROLLED COLUMN READING:")

names = np.genfromtxt(
    "employees.csv",
    delimiter=",",
    skip_header=1,
    usecols=0,
    dtype="U10",
    encoding="utf-8",
)
ages = np.genfromtxt(
    "employees.csv",
    delimiter=",",
    skip_header=1,
    usecols=1,
    dtype=int,
    encoding="utf-8",
)
salaries = np.genfromtxt(
    "employees.csv",
    delimiter=",",
    skip_header=1,
    usecols=2,
    dtype=float,
    encoding="utf-8",
    missing_values="",
    filling_values=np.nan,
)
depts = np.genfromtxt(
    "employees.csv",
    delimiter=",",
    skip_header=1,
    usecols=3,
    dtype="U15",
    encoding="utf-8",
)
genders = np.genfromtxt(
    "employees.csv",
    delimiter=",",
    skip_header=1,
    usecols=4,
    dtype="U1",
    encoding="utf-8",
)

print("\\nSeparate columns:")
print("Names: ", names)
print("Ages: ", ages)
print("Salaries: ", salaries)
print("Depts: ", depts)
print("Genders: ", genders)

# 5.5 DATA ANALYSIS
print("\n5.5 ANALYSIS ON LOADED DATA:")

print("Basic stats:")
print(f"  Avg Age: {np.mean(ages):.1f}")
print(f"  Avg Salary: {np.nanmean(salaries):.0f} TL")
print(f"  Missing salaries: {np.sum(np.isnan(salaries))}")

print("\nDept analysis:")
for dept in np.unique(depts):
    mask = depts == dept
    dept_sals = salaries[mask]
    valid_sals = dept_sals[~np.isnan(dept_sals)]
    if len(valid_sals) > 0:
        print(
            f"  {dept}: {len(valid_sals)} employees, Avg: {np.mean(valid_sals):.0f} TL"
        )


# 5.6 SAVING PROCESSED DATA
print("\n5.6 SAVING DATA:")
processed = np.column_stack((names, ages, salaries, depts, genders))
np.savetxt(
    "processed_employees.csv",
    processed,
    delimiter=",",
    fmt="%s",
    header="name,age,salary,dept,gender",
    comments="",
)
print("Saved to 'processed_employees.csv'")

# 5.7 PARAMETER REFERENCE
print("\n5.7 KEY PARAMETERS:")
params = {
    "delimiter": "Column separator (',', ';', '\t', ' ')",
    "skiprows": "Rows to skip",
    "usecols": "Columns to read",
    "dtype": "Data type (None, int, float, 'U10')",
    "encoding": "File encoding ('utf-8')",
    "missing_values": "Missing value marker",
    "filling_values": "Value to replace missing data",
}
for k, v in params.items():
    print(f"  {k}: {v}")

"""
FILE READING STRATEGIES:
- Clean numeric data: np.loadtxt()
- Complex/missing data: np.genfromtxt()
- Large files: Chunked reading (iterators)
- Custom formats: Pandas library
"""


=== 5. FILE OPERATIONS - np.loadtxt() & np.genfromtxt() ===

CSV created: employees.csv

5.2 np.loadtxt() - FOR SIMPLE FILES:
loadtxt() error: could not convert string '' to float64 at row 5, column 3.
Reason: Fails on missing data (NaN)

5.3 np.genfromtxt() - ADVANCED READING:
Data loaded with genfromtxt():
[('Jack', 25, 50000, 'Eng', 'M') ('Jim', 30, 60000, 'Sales', 'F')
 ('Jimmy', 35, 75000, 'Eng', 'M') ('Jill', 28, 55000, 'HR', 'F')
 ('John', 32, 48000, 'Sales', 'F') ('Janet', 29,     0, 'Eng', 'M')
 ('Jonathon', 27, 52000, 'HR', 'F') ('Jayson', 31, 68000, 'Sales', 'M')]
Data type:  [('f0', '<U8'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<U5'), ('f4', '<U1')]
Shape:  (8,)

5.4 CONTROLLED COLUMN READING:
\nSeparate columns:
Names:  ['Jack' 'Jim' 'Jimmy' 'Jill' 'John' 'Janet' 'Jonathon' 'Jayson']
Ages:  [25 30 35 28 32 29 27 31]
Salaries:  [50000. 60000. 75000. 55000. 48000.    nan 52000. 68000.]
Depts:  ['Eng' 'Sales' 'Eng' 'HR' 'Sales' 'Eng' 'HR' 'Sales']
Genders:  ['M' 'F' 'M' 'F' 

'\nFILE READING STRATEGIES:\n- Clean numeric data: np.loadtxt()\n- Complex/missing data: np.genfromtxt()\n- Large files: Chunked reading (iterators)\n- Custom formats: Pandas library\n'

In [37]:
# Step 1: Create data file
data = """85,90,,
92,,88,85
,78,82,90
"""

with open("exam_grades.csv", "w") as f:
    f.write(data)

# Step 2: Load
grades = np.genfromtxt("exam_grades.csv", delimiter=",", filling_values=np.nan)
print("Grades:\n", grades)

# Step 3: Calculate mean per column (per exam)
exam_means = np.nanmean(grades, axis=0)
print("Exam averages: ", exam_means)

# Step 4: Overall mean
overall_mean = np.nanmean(grades)
print("Overall class average: ", overall_mean)

Grades:
 [[85. 90. nan nan]
 [92. nan 88. 85.]
 [nan 78. 82. 90.]]
Exam averages:  [88.5 84.  85.  87.5]
Overall class average:  86.25


# Comprehensive Example

In [41]:
"""
Detailed, Explained NumPy Examples — Advanced Statistical Functions

This notebook demonstrates:
 - np.unique() & return_counts
 - np.bincount() for fast integer counting
 - np.histogram() for distribution analysis
 - Correlation & Covariance
 - Cumulative operations
 - Sorting & argsort
 - Financial analysis: Sharpe ratio, max drawdown
"""

print("\n" + "=" * 60)
print("=== 6. ADVANCED STATISTICAL FUNCTIONS ===\n")

# 6.1 np.unique() - UNIQUE VALUES & FREQUENCIES
print("6.1 np.unique() - UNIQUE VALUES:")
segments = np.array(["A", "B", "A", "C", "B", "A", "A", "C", "B", "A"])
print("Segments: ", segments)
unique_segs, freqs = np.unique(segments, return_counts=True)
print("Unique segments: ", unique_segs)
print("Frequencies: ", freqs)

for seg, freq in zip(unique_segs, freqs):
    pct = freq / len(segments) * 100
    print(f"  Segment {seg}: {freq} customers (%{pct:.1f})")

# 6.2 np.bincount() - FAST INTEGER COUNTING
print("\n6.2 np.bincount() - FAST INTEGER COUNTING:")
scores = np.array([5, 4, 3, 5, 2, 4, 5, 3, 4, 5, 1, 4, 5, 3, 2])
print("Scores: ", scores)
score_freq = np.bincount(scores)
print("Score frequencies (index=score): ", score_freq)
for s in range(1, len(score_freq)):
    print(f"  {s} stars: {score_freq[s]} customers")

# 6.3 np.histogram() - DATA DISTRIBUTION
print("\n6.3 np.histogram() - DISTRIBUTION:")
prices = np.array([45, 120, 85, 220, 150, 95, 180, 75, 250, 130, 65, 200, 110, 170, 90])
hist_freq, hist_bins = np.histogram(prices, bins=5)
print("Histogram freqs: ", hist_freq)
print("Histogram bins: ", hist_bins)
for i in range(len(hist_freq)):
    print(f"  {hist_bins[i]:.0f}-{hist_bins[i + 1]:.0f} TL: {hist_freq[i]} items")

# 6.4 CORRELATION & COVARIANCE
print("\n6.4 CORRELATION & COVARIANCE:")
income = np.array([25000, 32000, 28000, 45000, 38000, 29000, 41000])
expense = np.array([18000, 22000, 20000, 32000, 28000, 21000, 30000])
corr = np.corrcoef(income, expense)[0, 1]
cov = np.cov(income, expense)[0, 1]
print(f"Correlation: {corr:.3f}")
print(f"Covariance: {cov:.2f}")
if corr > 0.7:
    comment = "Strong positive"
elif corr > 0.3:
    comment = "Moderate positive"
elif corr > -0.3:
    comment = "Weak"
elif corr > -0.7:
    comment = "Moderate negative"
else:
    comment = "Strong negative"
print(f"Interpretation: {comment}")

# 6.5 CUMULATIVE OPERATIONS
print("\n6.5 CUMULATIVE OPERATIONS:")
monthly_sales = np.array([12000, 15000, 13000, 18000, 16000, 20000])
cum_sum = np.cumsum(monthly_sales)
cum_avg = cum_sum / np.arange(1, len(monthly_sales) + 1)
print("Cumulative Sum: ", cum_sum)
print("Cumulative Avg: ", cum_avg.astype(int))

# 6.6 SORTING & ARGSORT
print("\n6.6 SORTING & ARGSORT:")
sales = np.array([150, 85, 220, 95, 180, 65, 240, 130])
asc_idx = np.argsort(sales)
desc_idx = asc_idx[::-1]
print("Top 3 sellers: ", sales[desc_idx[:3]])
print("Bottom 3 sellers: ", sales[asc_idx[:3]])

# 6.7 FINANCIAL ANALYSIS
print("\n6.7 FINANCIAL ANALYSIS:")
returns = np.array([2.5, -1.2, 3.8, 0.5, -2.1, 4.2, 1.8, -0.9, 3.1, 2.8])
avg_ret = np.mean(returns)
vol = np.std(returns)
sharpe = avg_ret / vol
print(f"Avg Return: %{avg_ret:.2f}")
print(f"Volatility: %{vol:.2f}")
print(f"Sharpe Ratio: {sharpe:.2f}")

cum_ret = np.cumprod(1 + returns / 100)
peak = np.maximum.accumulate(cum_ret)
drawdown = (cum_ret - peak) / peak * 100
max_dd = np.min(drawdown)
print(f"Max Drawdown: %{max_dd:.2f}")

print("\n" + "=" * 60)
print("SESSION COMPLETE!")



=== 6. ADVANCED STATISTICAL FUNCTIONS ===

6.1 np.unique() - UNIQUE VALUES:
Segments:  ['A' 'B' 'A' 'C' 'B' 'A' 'A' 'C' 'B' 'A']
Unique segments:  ['A' 'B' 'C']
Frequencies:  [5 3 2]
  Segment A: 5 customers (%50.0)
  Segment B: 3 customers (%30.0)
  Segment C: 2 customers (%20.0)

6.2 np.bincount() - FAST INTEGER COUNTING:
Scores:  [5 4 3 5 2 4 5 3 4 5 1 4 5 3 2]
Score frequencies (index=score):  [0 1 2 3 4 5]
  1 stars: 1 customers
  2 stars: 2 customers
  3 stars: 3 customers
  4 stars: 4 customers
  5 stars: 5 customers

6.3 np.histogram() - DISTRIBUTION:
Histogram freqs:  [4 4 2 3 2]
Histogram bins:  [ 45.  86. 127. 168. 209. 250.]
  45-86 TL: 4 items
  86-127 TL: 4 items
  127-168 TL: 2 items
  168-209 TL: 3 items
  209-250 TL: 2 items

6.4 CORRELATION & COVARIANCE:
Correlation: 0.995
Covariance: 40500000.00
Interpretation: Strong positive

6.5 CUMULATIVE OPERATIONS:
Cumulative Sum:  [12000 27000 40000 58000 74000 94000]
Cumulative Avg:  [12000 13500 13333 14500 14800 15666]

6.

# `ufunc` (Universal Functions)

`ufunc`s are high-performance, element-wise functions in NumPy.

**Why use ufuncs?**
They apply vectorization, which is significantly faster than Python loops.
They also provide methods like reduction, accumulation, and broadcasting.

**Additional arguments:**
* `where`: Boolean array/condition defining where operations occur.
* `dtype`: Defines output type.
* `out`: Output array to store results.

In [42]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)
print(z)

z = np.add(x, y)
print(z)

[5, 7, 9, 11]
[ 5  7  9 11]


# How to Create Your Own `ufunc`
Define a normal Python function, then wrap it using `np.frompyfunc()`.

Arguments:\n",
* `function`: The Python function name.
* `inputs`: Number of input arrays.
* `outputs`: Number of output arrays.

In [43]:
def myadd(x, y):
    return x + y


myadd_ufunc = np.frompyfunc(myadd, 2, 1)
print(myadd_ufunc([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


# Arithmetic `ufunc`

In [44]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print(newarr)

newarr = np.subtract(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]


# Rounding Functions
Remove decimals and truncate toward zero using `trunc()` and `fix()`.

In [45]:
arr = np.trunc([-3.1666, 3.6667])
print(arr)

arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  3.]


`around()` rounds to the nearest value (>=.5 rounds up). <br>
Example: `np.around(3.1666, 2) = 3.17`"

In [46]:
arr = np.around(3.1666, 2)
print(arr)

3.17


In [48]:
print("\n" + "=" * 60)
print("=== 2. MATHEMATICAL UFUNCS ===\n")

# 2.1 BASIC ARITHMETIC
print("2.1 BASIC ARITHMETIC UFUNCS:")
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])
print("x: ", x)
print("y: ", y)
print("\nBasic Operations:")
print("Add: ", np.add(x, y))
print("Subtract: ", np.subtract(y, x))
print("Multiply: ", np.multiply(x, y))
print("Divide: ", np.divide(y, x))
print("Power: ", np.power(x, 2))
print("Sqrt: ", np.sqrt(x))

# 2.2 MOD & DIVISION
print("\n2.2 MOD & DIVISION:")
print("Floor Div: ", np.floor_divide(y, x))
print("Mod: ", np.mod(y, x))
quot, rem = np.divmod(y, x)
print("  Quotient: ", quot)
print("  Remainder: ", rem)

# 2.3 ABS & SIGN
print("\n2.3 ABSOLUTE & SIGN:")
vals = np.array([-5, 3.7, -2.1, 0, 8.9, -0.5])
print("Abs: ", np.absolute(vals))
print("Sign: ", np.sign(vals))

# 2.4 ROUNDING
print("\n2.4 ROUNDING:")
decimals = np.array([3.14159, 2.71828, 1.41421, 5.6789, 9.8765])
print("Round(2): ", np.round(decimals, 2))
print("Floor: ", np.floor(decimals))
print("Ceil: ", np.ceil(decimals))

# 2.5 LOGARITHMS
print("\n2.5 LOGARITHMS:")
pos = np.array([1, 10, 100, 1000, 10000])
print("Log: ", np.log(pos))
print("Log10: ", np.log10(pos))
print("Log2: ", np.log2(pos))

# 2.6 FINANCIAL CALCULATIONS
print("\n2.6 FINANCIAL APP:")
principal = np.array([1000, 5000, 10000, 20000])
rate = 0.08
years = np.array([1, 3, 5, 10])
fv = principal * np.power(1 + rate, years)
print("Future Values: ", fv.astype(int))

start = 10000
end = np.array([11000, 12500, 15000, 18000])
cagr = np.power(end / start, 1 / 5) - 1
print(f"CAGR: % {(cagr * 100).round(2)}")



=== 2. MATHEMATICAL UFUNCS ===

2.1 BASIC ARITHMETIC UFUNCS:
x:  [1 2 3 4 5]
y:  [10 20 30 40 50]

Basic Operations:
Add:  [11 22 33 44 55]
Subtract:  [ 9 18 27 36 45]
Multiply:  [ 10  40  90 160 250]
Divide:  [10. 10. 10. 10. 10.]
Power:  [ 1  4  9 16 25]
Sqrt:  [1.         1.41421356 1.73205081 2.         2.23606798]

2.2 MOD & DIVISION:
Floor Div:  [10 10 10 10 10]
Mod:  [0 0 0 0 0]
  Quotient:  [10 10 10 10 10]
  Remainder:  [0 0 0 0 0]

2.3 ABSOLUTE & SIGN:
Abs:  [5.  3.7 2.1 0.  8.9 0.5]
Sign:  [-1.  1. -1.  0.  1. -1.]

2.4 ROUNDING:
Round(2):  [3.14 2.72 1.41 5.68 9.88]
Floor:  [3. 2. 1. 5. 9.]
Ceil:  [ 4.  3.  2.  6. 10.]

2.5 LOGARITHMS:
Log:  [0.         2.30258509 4.60517019 6.90775528 9.21034037]
Log10:  [0. 1. 2. 3. 4.]
Log2:  [ 0.          3.32192809  6.64385619  9.96578428 13.28771238]

2.6 FINANCIAL APP:
Future Values:  [ 1080  6298 14693 43178]
CAGR: % [ 1.92  4.56  8.45 12.47]
