# 1. What is NumPy? Why do we use it?

* NumPy (Numerical Python) is a fundamental library in Python for scientific computing.

* It provides high-performance, multidimensional arrays and matrices along with tools to work with them:

* ndarray: Multidimensional, homogeneous, and high-performance array objects.

## Why not use regular lists instead?
1. Speed: NumPy is implemented in C under the hood, providing faster access to elements and enabling vectorized operations without loops.
2. Functions: It comes with built-in functions for linear algebra, statistics, Fourier transforms, etc., making complex computations more efficient.
3. Broadcasting: NumPy allows easy element-wise operations between arrays of different shapes through a feature called broadcasting.



In [6]:
import numpy as np

# Introduction to NumPy: Why is it needed?

| Özellik    | Python Array                                                                        | NumPy Array (ndarray)                                                      |
|------------|-------------------------------------------------------------------------------------|----------------------------------------------------------------------------|
| Data Type  | Can hold mixed types (like int, string, float) at the same time.                    | Contains only a single type of data (all integers, all floats, etc.).      |
| Speed      | Slow. Each element is stored separately; looping is required to perform operations. | Very fast. All elements are stored side by side in a single memory block.       |
| İşlem Tipi | Cannot perform element-wise mathematical operations.                         | Can perform vectorized operations (executes thousands of operations simultaneously with a single command). |



## Analogies:

- Python List: A shopping cart containing items of various shapes and sizes, where you have to individually inspect and process each item
- NumPy Array: A well-organized package containing only identical items (e.g., all apples) with the same weight. You can process th entire package at once.

## Memory Usage

In [5]:
import sys

python_list = [1, 2, 3, 4]
print("Memory usage of Python lists:", sys.getsizeof(python_list), "bytes")

Memory usage of Python lists: 88 bytes


In [7]:
numpy_array = np.array([1, 2, 3, 4])
print("Memory usage of Python list: ", numpy_array.nbytes, "bytes")

Memory usage of Python list:  32 bytes


In [8]:
import time

py_list = list(range(1000000))
t1 = time.time()
result_py = [x * 2 for x in py_list]
t2 = time.time()
print("Python list time: ", t2 - t1)

np_array = np.array(py_list)
t3 = time.time()
result_np = np_array * 2
t4 = time.time()
print("Numpy array time: ", t4 - t3)

Python list time:  0.0300447940826416
Numpy array time:  0.0002739429473876953


In [9]:
a = np.array([1, 2, 3, 4, 5])

a

array([1, 2, 3, 4, 5])

In [10]:
a = np.array((1, 2, 3, 4))

type(a)

numpy.ndarray

In [11]:
empty_array = np.array([])
empty_array

array([], dtype=float64)

Array Size Settings

In [13]:
# Single dimension array
a = np.array([1, 2, 3, 4])
print(a)
print("Size: ", a.ndim)
print("Array size: ", a.shape)
print("Number of elements in the array: ", a.size)
print("Type of array: ", a.dtype)

[1 2 3 4]
Size:  1
Array size:  (4,)
Number of elements in the array:  4
Type of array:  int64


In [15]:
# Double dimensions array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print("Size: ", b.ndim)
print("Array size: ", b.shape)
print("Number of elements in the array: ", b.size)
print("Type of array: ", b.dtype)

[[1 2 3]
 [4 5 6]]
Size:  2
Array size:  (2, 3)
Number of elements in the array:  6
Type of array:  int64


In [16]:
# Three Dimensions array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)
print("Size: ", c.ndim)
print("Array size: ", c.shape)
print("Number of elements in the array: ", c.size)
print("Type of array: ", c.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Size:  3
Array size:  (2, 2, 3)
Number of elements in the array:  12
Type of array:  int64


In [17]:
# Creating special arrays

# array with zeroes
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [18]:
# array with ones
ones_array = np.ones((2, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
fives_array = np.full((2, 3), 5)
print(fives_array)

[[5 5 5]
 [5 5 5]]


In [20]:
# Identity matrix
b = np.eye(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# Within a specific range
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Basic Properties of Arrays

shape - boyut (satir, sutun)
ndim - sekil (kac boyutlu)
dtype - veri tipi (dizinin tipi)
size - dizideki toplam elemna sayisi


In [24]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

print("Shape: ", matrix.shape)
print("ndim: ", matrix.ndim)
print("dtype: ", matrix.dtype)
print("Size: ", matrix.size)
print("Itemsize: ", matrix.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
ndim:  2
dtype:  int64
Size:  9
Itemsize:  8


# Main Arithmetical

In [33]:
# Scalar array operations

a = np.array([10, 20, 30, 40, 50])
scaler = 5
print("Addition.      : ", (a + scaler))
print("Multiplication : ", (a * scaler))
print("Subtraction    : ", (a - scaler))
print("Division       : ", (a / scaler))


Addition.      :  [15 25 35 45 55]
Multiplication :  [ 50 100 150 200 250]
Subtraction    :  [ 5 15 25 35 45]
Division       :  [ 2.  4.  6.  8. 10.]


In [34]:
# Operations on multi-dimensional arrays

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[10, 20], [30, 40]])
print("Addition       : ", array1 + array2)
print("Multiplication : ", array1 * array2)
print("Subtraction    : ", array1 - array2)
print("Division       : ", array1 / array2)

Addition       :  [[11 22]
 [33 44]]
Multiplication :  [[ 10  40]
 [ 90 160]]
Subtraction    :  [[ -9 -18]
 [-27 -36]]
Division       :  [[0.1 0.1]
 [0.1 0.1]]


In [42]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("Addition       : ", a + b)
print("Multiplication : ", a * b)
print("Subtraction    : ", a - b)
print("Division       : ", a / b)

# Element-wise operations on arrays
a_p = [10, 20, 30, 40]
b_p = [1, 2, 3, 4]

print("a_p + b_p : ", a_p + b_p)

sum_a_b = []
for i in range(len(a_p)):
    sum_a_b.append(a_p[i] + b_p[i])
print(sum_a_b)

Addition       :  [11 22 33 44]
Multiplication :  [ 10  40  90 160]
Subtraction    :  [ 9 18 27 36]
Division       :  [10. 10. 10. 10.]
a_p + b_p :  [10, 20, 30, 40, 1, 2, 3, 4]
[11, 22, 33, 44]


# Broadcasting

A mechanism that enables operations between arrays od different shapes.


When NumPy performs operations between arrays of different shapes, it automatically broadcasts the smaller (or one-dimensional) array, effectively expanding it to match the larger shape as if it were replicated

_Core Rule: The smaller array is broadcast (conceptually repeated) to match the shape of the larger array. Array dimensions are compared from right to left. Two dimensions are compatible if they are equal or if one of them is 1._


In [44]:
a = np.array([10, 20, 30])  # [10, 20, 30]
b = 5  # scalar value ->      [5, 5, 5]
print(a + b)

[15 25 35]


In [ ]:
matrix_ = np.array([[1, 2, 3], [4, 5, 6]])
print("matrix: ", matrix_)
vector_ = np.array([10, 20, 30])
print("Vector: ", vector_)  # -> [10, 20, 30]  -> [10, 20, 30], [10, 20, 30]
result = matrix_ + vector_
print("Result: ", result)

matrix:  [[1 2 3]
 [4 5 6]]
Vector:  [10 20 30]
Result:  [[11 22 33]
 [14 25 36]]


## Broadcasting Rules (Compatibility Conditions)

For two arrays to be broadcastable, their shapes are compared from right to left. For each corresponding dimension, one of the following must hold:
1. The dimensions are equal (e.g., 3 and 3)
2. One of the dimensions is 1 (e.g., 5 and 1, or 1 and 7)

Otherwise, NumPy raises a ValueError: operands could not be broadcast together....

In [57]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix:\n", matrix)
print("Matrix + 10:\n", matrix + 10)

print("---------")
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
b = np.array([10, 20])  # shape: (2,)

try:
    print(
        a + b
    )  # ValueError: operands could not be broadcast together with shapes (2,3) (2,)
except ValueError as e:
    print("HATA:", e)

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix + 10:
 [[11 12 13]
 [14 15 16]]
---------
HATA: operands could not be broadcast together with shapes (2,3) (2,) 


In [62]:
# Storing temperature, humidity, and wind speed measurements from a weather station as a NumPy array.

# One-Dimensional Array: A single series of sequential measurements from a device (e.g., temperatures)
temperatures = np.array([22.5, 23.1, 22.9, 23.5, 24.0])
print(f"Daily Temperatures: {temperatures}°C")

# Two-Dimensional Array: Simultaneous measurements from different sensors (Matrix) [Temperature, Humidity, Wind Speed]
weather_data = np.array([[22.5, 55.0, 15.0], [23.1, 52.5, 18.0], [22.9, 53.0, 16.5]])
print(f"\nMulti-sensor weather data:\n {weather_data}")

Daily Temperatures: [22.5 23.1 22.9 23.5 24. ]°C

Multi-sensor weather data:
 [[22.5 55.  15. ]
 [23.1 52.5 18. ]
 [22.9 53.  16.5]]


In [ ]:
# Converting Celsius to Fahrenheit using NumPy arrays.
celsius_temperature = np.array([10.0, 15.0, 20.0])
fahrenheit_temperature = (celsius_temperature * 9 / 5) + 32
print(f"Fahrenheit Temperatures: {fahrenheit_temperature}")

Fahrenheit Temperatures: [50. 59. 68.]


In [65]:
# Converting Celsius to Fahrenheit using a loop (Python list)
celsius_temperature = [10, 15.0, 20.0]
fahrenheit_temperature = []
for temperatures in celsius_temperature:
    fahrenheit_temperature.append(temperatures * 9 / 5 + 32)

print(f"Fahrenheit Temperatures: {fahrenheit_temperature}")

Fahrenheit Temperatures: [50.0, 59.0, 68.0]
